eureka:
  client:
    service-url: 
      defaultZone: "http://localhost:8761/eureka/"
      
---
spring:	spring:
  profiles: subject
words: I,You,He,She,It

 ---	---
spring:	spring:
  profiles: verb
words: ran,knew,had,saw,bought


 ---	---
spring:	spring:
  profiles: article
words: a,the

 ---	---
spring:	spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely


 ---	---
spring:	spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog
      
  
